[tox]
env_list = py311, py312, py313, py314
min_version = 4.0
skip_missing_interpreters = true

[testenv]
package = skip
deps =
    pytest
    pytest-cov
commands = pytest {posargs}

[testenv:coverage]
base_python = py311
commands =
    python -c "from pathlib import Path; Path(r'{env:COVERAGE_DIR:coverage}').mkdir(parents=True, exist_ok=True)"
    pytest --cov=summem --cov-report=lcov:{env:COVERAGE_DIR:coverage}/lcov.info {posargs}
